DROP FUNCTION IF EXISTS fn_BookBorrowingFrequency;
GO
CREATE FUNCTION fn_BookBorrowingFrequency
(
    @BookID INT
)
RETURNS INT
AS
BEGIN
	RETURN (SELECT COUNT(*) FROM Loans WHERE BookID = @BookID);
END;
GO